name: mugup
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_svg: ^2.1.0
  package_info_plus: ^8.3.0
  either_dart: ^1.0.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/svg/



  fonts:
      - family: Popins
        fonts:
          - asset: assets/fonts/poppins/Poppins-Bold.ttf
            style: normal
            weight: 700

      - family: Popins
        fonts:
          - asset: assets/fonts/poppins/Poppins-SemiBold
            style: normal
            weight: 600

      - family: Popins
        fonts:
          - asset: assets/fonts/poppins/Poppins-Medium.ttf
            style: normal
            weight: 500


      - family: Popins
        fonts:
          - asset: assets/fonts/poppins/Poppins-Regular.ttf
            style: normal
            weight: 400

